# Generated by Django 3.2.8 on 2022-06-01 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0017_auto_20220529_2037'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_tt', models.CharField(db_column='code_tt', max_length=255, verbose_name='Код ТТ')),
                ('status', models.CharField(db_column='status', max_length=255, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Исключение',
                'verbose_name_plural': 'Исключения',
            },
        ),
        migrations.AlterModelOptions(
            name='report770file',
            options={'verbose_name': 'Загрузка 770', 'verbose_name_plural': 'Загрузка 770'},
        ),
        migrations.AlterModelOptions(
            name='reportfile',
            options={'verbose_name': 'Загрузка 07 и 145', 'verbose_name_plural': 'Загрузка 07 и 145'},
        ),
    ]
